### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by hedjour** [BIOP/biop-bash-scripts#12]
I have more problem with proxy settings.
I set the proxy in environment variable, I have set Proxy in graphical interface of fiji,
I try this commands :
```
"$fiji_path" "$proxy_info" --ij2 --headless --run InstallQuPathExtension.groovy "$all_args"
~/abba/Fiji.app/ImageJ-win64.exe -Dhttps.proxyHost=proxyserver -Dhttps.proxyPort=proxyport --ij2 --headless --run InstallQuPathExtension.groovy
```

I get these error :
```java
Starting download
[ERROR] java.net.UnknownHostException
```
Many times I get a connection error timed out.

**Comment by NicoKiaru** [comment]
Just to understand: it fails all the time or is it failing after a certain amount of connections have been reached ?

If it's failing all the time, it's maybe because the proxy is ignored here:

https://github.com/BIOP/biop-bash-scripts/blob/dc7aad5b5bbb10c6cd352c694025afea1427e208/InstallQuPathExtension.groovy#L118

I did not think about the proxy possibility. It's probably possible to use it, I need to check how to get the proxy settings from the current iamgej instance.

**Comment by NicoKiaru** [comment]
ChatGPT mentions this solution:

```
System.setProperty("http.proxyHost", "your_proxy_host");
System.setProperty("http.proxyPort", "your_proxy_port");
System.setProperty("https.proxyHost", "your_proxy_host");
System.setProperty("https.proxyPort", "your_proxy_port");

try {
    FileUtils.copyURLToFile(url, destinationFile);
} catch (IOException e) {
    e.printStackTrace();
}

// Be sure to reset the proxy settings after you're done
System.clearProperty("http.proxyHost");
System.clearProperty("http.proxyPort");
System.clearProperty("https.proxyHost");
System.clearProperty("https.proxyPort");
```

The thing is that I don't know whether it's not already the method implemented in Fiji.

Maybe you can try to manually add these lines with your proxy settings to the InstallQuPathExtension script and see if it works. If it works, then I'll try to make it cleaner

**Comment by hedjour** [comment]
Yes I will try on windows. For explanation download works for fiji, qpath, but not for fiji in CLI but works in fiji GUI...

**Comment by NicoKiaru** [comment]
Lucky us!
