### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by hedjour** [BIOP/biop-bash-scripts#15]
Is it possible to use the same jar file for Qupath and Fiji in case of abba and full install scripts ?

**Comment by NicoKiaru** [comment]
Hmm QuPath has plenty of jars and Fiji as well. When you run 'Fiji', what's actually runned is a native executable that performs a bunch of tasks (checking for updates for instance) and only later this executable starts java with a main entry point.
For QuPath I don't know exactly how it works. 

Both Fiji and QuPath ship their own java, but a different one (Java 8 for Fiji, I think Java 11 or 14 for QuPath).

I think it's possible to run a simple java piece of code within a single jar, but we would need a jdk in order to run something like:

```
java -jar install.jar arg0 arg1
```

Still we would need to use one of these jdks. A way would be to use Fiji's jdk for Fiji's related installation, and QuPath jdk for QuPath related installation.

**Comment by hedjour** [comment]
Oki a very complex system for a minimal gain. A false good idea
